### ISSUE TITLE
docs: Update to Explore Profiles docs for new UI and feature changes week of July 29-Aug 2

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/explore-profiles#98]
Weekly doc issue to capture any doc updates for changes to UI and features in the plugin. 

List of PRs from July 19-July 26 that have UI changes impacting users: 
* https://github.com/grafana/explore-profiles/pull/94
* https://github.com/grafana/explore-profiles/pull/93
* https://github.com/grafana/explore-profiles/pull/81
* https://github.com/grafana/explore-profiles/pull/76
* https://github.com/grafana/explore-profiles/pull/92

```[tasklist]
### Tasks
- [ ] Check new features against screenshots 
- [ ] Update any screenshots that need to be changed
- [ ] Verify UI elements match what is in the docs 
```

**Comment by 09jvilla** [comment]
I slightly modified the title to clarify it was for Explore Profiles (which was hard to tell in the "board" view, even though you can tell in this view pretty easily since its in the Explore Profiles repo). 

My understanding would be that this issue (98) is a blocker/requisite for https://github.com/grafana/explore-profiles/issues/112, correct?

**Comment by knylander-grafana** [comment]
> I slightly modified the title to clarify it was for Explore Profiles (which was hard to tell in the "board" view, even though you can tell in this view pretty easily since its in the Explore Profiles repo).
> 
> My understanding would be that this issue (98) is a blocker/requisite for [grafana/pyroscope-squad#238](https://github.com/grafana/pyroscope-squad/issues/238), correct?

Because of the timing, the changes for this issue are being done concurrent with the Explore Profiles doc issue for the preview release. This issue was created when my plan was to update docs on for Explore Profiles every other week. That didn't pan out, so instead I created the preview release issue and left this issue open because it lists the PRs. 

I might be able to mark this one as closed and just use the other issue.

**Comment by knylander-grafana** [comment]
Closing this doc issue in favor of https://github.com/grafana/pyroscope-squad/issues/238
I've moved my notes from this issue to the other one.
